### ISSUE TITLE
AttributeError: 'WindowsPath' object has no attribute 'shape'

### ISSUE THREAD

**Issue by hxm-cpp** [garibida/cross-image-attention#5]
i setup in a new env everything, when i execute

```
python run.py ^
--app_image_path  C:/1091588.jpg ^
--struct_image_path C:/aurora_borealis_hd.jpg ^
--output_path C:/output.jpg ^
--domain_name sky ^
--contrast_strength 1.67 ^
--swap_guidance_scale 3.5 
```
i got : 
```
Traceback (most recent call last):
  File "D:\cross-image-attention\run.py", line 65, in <module>
    main()
  File "D:\cross-image-attention\cross_image_attention\lib\site-packages\pyrallis\argparsing.py", line 158, in wrapper_inner
    response = fn(cfg, *args, **kwargs)
  File "D:\cross-image-attention\run.py", line 21, in main
    run(cfg)
  File "D:\cross-image-attention\run.py", line 28, in run
    latents_app, latents_struct, noise_app, noise_struct = load_latents_or_invert_images(model=model, cfg=cfg)
  File "D:\cross-image-attention\utils\latent_utils.py", line 22, in load_latents_or_invert_images
    app_image, struct_image = image_utils.load_images(cfg=cfg, save_path=cfg.output_path)
  File "D:\cross-image-attention\utils\image_utils.py", line 11, in load_images
    image_style = load_size(cfg.app_image_path)
  File "D:\cross-image-attention\utils\image_utils.py", line 30, in load_size
    h, w, c = image.shape
AttributeError: 'WindowsPath' object has no attribute 'shape'
```

i'm on Python 3.10.6

**Comment by yuval-alaluf** [comment]
The code is not designed to work with windows and I assume that `pyrallis` parsed the paths as `str` rather than `Path`, although it seems like the code should have handled both cases: 
https://github.com/garibida/cross-image-attention/blob/f724d1aea1e0b91d8892b512d829cccbc2b046d8/utils/image_utils.py#L25-L28
I would assume that the problem is in the above lines. You can try debugging and see if you notice the problem. If you find a solution, feel free to let me know and I'll try uploading a fix. I can't test this myself since I don't have windows :)

**Comment by hxm-cpp** [comment]
i made this change, it seems to work fine.
```diff
-    if type(image_path) is str or type(image_path) is pathlib.PosixPath:
-        image = np.array(Image.open(image_path).convert('RGB'))
+    if isinstance(image_path, (str, pathlib.Path)):
+        image = np.array(Image.open(str(image_path)).convert('RGB'))    
     else:
         image = image_path
 
-    h, w, c = image.shape
+    h, w, _ = image.shape
```

**Comment by hxm-cpp** [comment]
https://github.com/garibida/cross-image-attention/pull/7
